### ISSUE TITLE
cloudflare need a paid plan to use it?

### ISSUE THREAD

**Issue by yaoyi2008** [emadda/worker-tabserve-reverse-proxy#1]
➜  worker-tabserve-reverse-proxy git:(master) ✗ wrangler deploy
 ⛅️ wrangler 3.1.1
------------------
Your worker has access to the following bindings:
- Durable Objects:
  - REV_PROXY_DO: REV_PROXY_DO
- Vars:
  - ENV: "prod"
  - AUTH_TOKEN: "PROD_an_example_auth_token_replace_in..."
  - USE_WS_HIBERNATION: "1"
Total Upload: 284.68 KiB / gzip: 54.66 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/***mask***/workers/scripts/worker-tabserve-reverse-proxy) failed.

  In order to use Durable Objects, you must switch to a paid plan at
  https://dash.cloudflare.com/***mask**/workers/plans
  [code: 10084]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by emadda** [comment]
Yes, I am afraid you will need a paid plan for this.

I think it is $5 per month or less though.

**Comment by rubickecho** [comment]
> Yes, I am afraid you will need a paid plan for this.
> 
> I think it is $5 per month or less though.

ok, I think this information can be explained in the README.

**Comment by emadda** [comment]
It is explained in the Intro at [tabserve.dev](https://tabserve.dev) and on the Cloudflare Workers page too.

Thanks, I will add a line in this repo for people who have missed it.

**Comment by rubickecho** [comment]
sorry, It's my fault, I didn't read it carefully.

![image](https://github.com/emadda/worker-tabserve-reverse-proxy/assets/14804014/a1b5ee2f-6c86-41ea-bd3f-e497ed02b82e)
